version: '3.9'

services:
  ef-migrator:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - .:/app
      - ./App_Data:/app/App_Data
      - .:/app:cached
    working_dir: /app
    entrypoint: ["/bin/bash", "/app/entrypoint.sh"]
